### ISSUE TITLE
http://localhost:9000 not working

### ISSUE THREAD

**Issue by RDDOUB** [linkedin/WhereHows#140]
I have backend service and web running, but when I go to http://localhost:9000 it doesn't do anything. Running on Ubuntu Linux server with a private IP.

**Comment by rkluszczynski** [comment]
Hello Ryan,
just letting you know, that in case of web module for me works simply:

> git clone https://github.com/linkedin/WhereHows.git
> wget http://downloads.typesafe.com/play/2.2.4/play-2.2.4.zip
> unzip play-2.2.4.zip
> export PLAY_HOME=`pwd`/play-2.2.4/
> cd WhereHows/
> ./gradlew clean build
> cd web/
> $PLAY_HOME/play run

and then address http://localhost:9000 works showing logging page. Of course, you will not be able to create an account if you not set database connection properties in **web/conf/application.conf** file.

The same goes to backend-service, but here you have to first set up tables correctly (see https://github.com/linkedin/WhereHows/blob/master/data-model/DDL/readme.MD) in order to start the service. Address http://localhost:9000 should just print "TEST" in your browser:)

HTH:)

**Comment by useracn** [comment]
hello, i followed this instructions and able to successfully clean build. I can't see the play run application in play-2.2.4 folder. I'm using v1.0 wherehows tag.

**Comment by kopollo** [comment]
You can find many solutions about localhost here -> <a rel="ffnofollowsd" href="https://localhosts.mobi/:9000">https://localhosts.mobi/:9000</a>
