### ISSUE TITLE
can't add comments

### ISSUE THREAD

**Issue by jimmy-src** [linkedin/WhereHows#1460]
v1.0.0

![image](https://user-images.githubusercontent.com/12254857/48815715-5f920c00-ed7a-11e8-9df7-c761a7968a04.png)

![image](https://user-images.githubusercontent.com/12254857/48815739-79335380-ed7a-11e8-9f88-c74a870f0e9c.png)

click save no response and no log.

How to resolve this? Thanks

**Comment by Ash-Mishra** [comment]
The problem is due to invalid token value. The form is not getting any token so it is not able to make any post request. So instead of toke just substitute ''(empty string) in dataset-comments.js.
Go to dataset-comments.js near line 218 there is create function. In that replace the token assignment to- 
`var token = $("#csrfToken").val()?$("#csrfToken").val().replace('/', ''):'';`

**Comment by jimmy-src** [comment]
it works!

@Ash-Mishra thanks!
