### ISSUE TITLE
[Datahub] Error bootstrapping Data Hub

### ISSUE THREAD

**Issue by arpan34** [linkedin/WhereHows#1497]
Hi,

I am getting AvroTypeException error running `python mce_cli.py produce -d bootstrap_mce.dat`

**Comment by RealChrisL** [comment]
Hello @arpan34 ,

Welcome landing on the  Data Hub. Please note this branch is still WIP as of now. Nonetheless, we plan to announce the first official release soon. Stay in tune!

As for your issue in the AvroTypeException, if you are leveraging the opensource version `mce.dat` file, please make sure your python libraries are satisfied with the requirement.txt.

On the other hand, if you are in the case to build your own `MetadataChangeEvent`, please be aware of our framework is aligned with the `fastavro` library to serialize/deserialize the data with Kafka.

Therefore, the union types annotation in the `MetadataChangeEvent` schema should be the tuple of `(type, data)` instead of just data. Please refer to the issue here: fastavro/fastavro#191.

Chris

**Comment by arpan34** [comment]
Hi @RealChrisL,

Thanks for the quick response. I am leveraging the opensourced `bootstrap_mce.dat` file. Also, I have the dependency with the same version as mentioned in the requirements.txt but I am still getting the exception. 
Stack trace:

`Arpans-MBP:mce-cli arpan$ python mce_cli.py produce -d bootstrap_mce.dat
Producing MetadataChangeEvent records to topic MetadataChangeEvent. ^c to exit.
Traceback (most recent call last):
  File "mce_cli.py", line 107, in <module>
    main(parser.parse_args())
  File "mce_cli.py", line 89, in main
    produce(conf, args.data_file)
  File "mce_cli.py", line 33, in produce
    producer.produce(topic=topic, value=content)
  File "/Library/Python/2.7/site-packages/confluent_kafka/avro/__init__.py", line 80, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "/Library/Python/2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 113, in encode_record_with_schema
    return self.encode_record_with_schema_id(schema_id, record, is_key=is_key)
  File "/Library/Python/2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 147, in encode_record_with_schema_id
    writer(record, outf)
  File "/Library/Python/2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 84, in <lambda>
    return lambda record, fp: writer.write(record, avro.io.BinaryEncoder(fp))
  File "/Library/Python/2.7/site-packages/avro/io.py", line 1042, in write
    raise AvroTypeException(self.writers_schema, datum)
avro.io.AvroTypeException: The datum {'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.CorpUserSnapshot', {'urn': 'urn:li:corpuser:datahub', 'aspects': [{'active': True, 'fullName': 'Data Hub', 'displayName': 'Data Hub', 'email': 'datahub@linkedin.com'}, {}]}), 'proposedDelta': None} is not an example of the schema {
  "doc": "Kafka event for proposing a metadata change for an entity. A corresponding MetadataAuditEvent is emitted when the change is accepted and committed, otherwise a FailedMetadataChangeEvent will be emitted instead.", 
  "type": "record", 
  "namespace": "com.linkedin.pegasus2avro.mxe", 
  "name": "MetadataChangeEvent", 
  "fields": [
    {
      "default": null, 
      "doc": "Kafka audit header. See go/kafkaauditheader for more info.", 
      "type": [
`

**Comment by RealChrisL** [comment]
Hi, @arpan34 ,

Thanks for participating in our early launching, we updated the dependency with `confluent-kafka[avro]` to make sure the `fastavro` can be successfully imported. Would you please to confirm the library also installed?

In the meantime, since we cannot reproduce the issue in our side, if the issue persists, please provide us your environment configurations (operating system, python version ...etc) for further debugging, thank you very much!

Chris

**Comment by arpan34** [comment]
The problem is resolved after installing `fastavro`.  Thanks @RealChrisL !
