### ISSUE TITLE
我们是否可以嵌入自己的任务调度系统吗

### ISSUE THREAD

**Issue by PettterPan** [linkedin/WhereHows#257]
```
 Hi ， 请问一下，能不能将自定义的任务调度系统嵌入到wherehows，对产生的上下游数据进行血缘分析。
如果可以的话，那应该注意什么问题，谢谢
```

**Comment by superwood** [comment]
你自己仿造 azkaban的抽取实现自己的抽取脚本。 抽取出来的数据尽量符合azkaban抽取出来的数据接口

**Comment by ericsun2** [comment]
@PettterPan, WhereHows team is working on a Kafka-based lineage ingestion pipeline, which aims at reporting lineage by the job executor itself. In short, whenever a data movement/ETL job finishes successfully, the post-execution codes will extract the lineage info out of the execution context/log, and then pack them into a Kafka message. 
Does this sound like a good integration interface to your use cases?

If you prefer a batch-oriented lineage extraction, then @superwood's comment is right. You can create a new job type called XYZ_LINEAGE_METADATA_ETL and implement specific extract and cleansing logic. @alyiwang can discuss more details with you in an offline thread.

If you'd like to invoke the metadata ETL jobs based on the cadence defined inside your own orchestrator, WhereHows needs one API to modify the "next_run" epoch of the defined job entry in wh_etl_job, so that this particular job will be executed soon. There's more detail to figure out, please elaborate your use case to help us understand better.

The backend service has a mini crontab (https://github.com/linkedin/WhereHows/wiki/Backend-API#etl-job-schedule). See if we can extend that to suit your needs.

**Comment by PettterPan** [comment]
@superwood 嗯 ，谢谢， 我们调度系统中有很多非hadoop的任务，现在正在手动调试

**Comment by PettterPan** [comment]
@ericsun2 thank you very much. the project of Wherehows is very useful.Our project need the batch-oriented lineage  extraction, So I will follow  @superwood's  method to achieve . thank you very much.

**Comment by diaowenyang** [comment]
@PettterPan How to get lineage info from wherehows,can you help me ?
