### ISSUE TITLE
Change DB's charset to utf8mb4 from utf8

### ISSUE THREAD

**Issue by tsukaby** [linkedin/WhereHows#501]
MySQL utf8 can't save a 4bytes character.
I think that is better to change DB's charset set to utf8mb4.

How do you think about it?
Thank you!

**Comment by alyiwang** [comment]
Thanks @tsukaby for bring this up!
Currently utf8 Char set works fine with all our use cases. If you use cases requires utf8mb4 for special characters, you are welcome to change this when creating the tables, it shouldn't affect WhereHows functions. 
For now, we don't have plan to change the default char set since it involves database evolution.

**Comment by tsukaby** [comment]
> involves database evolution

OK. I see. 
I will stop PR.

Thank you @alyiwang
