### ISSUE TITLE
The link for downloading WhereHows VM is unaccessable

### ISSUE THREAD

**Issue by leopoda** [linkedin/WhereHows#77]
Seems the link below to download WhereHows VM is unaccessable:

https://linkedin.app.box.com/wherehows-demo-in-cloudera-vm

Could anyone help to provide a valid link?

**Comment by SunZhaonan** [comment]
It works for me. What does it show after you open the link?

**Comment by leopoda** [comment]
@SunZhaonan
thanks for your quick responding. 
When I open the link, the server responds with error code: ERR_CONNECTION_TIMED_OUT. I tried many proxy servers, but no help :(

Thanks,
Jianbin

**Comment by SunZhaonan** [comment]
I guess it's because China's GFW block `*app.box.com` domain ：[link](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E8%A2%AB%E5%B0%81%E9%94%81%E7%BD%91%E7%AB%99%E5%88%97%E8%A1%A8#)

On my machine:

$ ping linkedin.app.box.com
PING linkedin.app.box.com (74.112.185.87): 56 data bytes
64 bytes from 74.112.185.87: icmp_seq=0 ttl=53 time=23.406 ms
64 bytes from 74.112.185.87: icmp_seq=1 ttl=53 time=22.123 ms
64 bytes from 74.112.185.87: icmp_seq=2 ttl=53 time=20.438 ms

I'll try if I can upload into 百度云盘 or 网易云网盘.

**Comment by ericsun2** [comment]
app.box.com is indeed blocked in China :-1:

**Comment by leopoda** [comment]
I mapped the IP 74.**112.185.87** to **linkedin.app.box.com** in the hosts file, and the URL can be accessed now.

Thanks very much for the help.
