### ISSUE TITLE
Build error with gradle plugin

### ISSUE THREAD

**Issue by leopoda** [linkedin/WhereHows#89]
Administrator@Win7 MINGW64 ~/repo/WhereHows (master)
$ gradle build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'WhereHows'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.12.0.
     Required by:
         :WhereHows:unspecified
      > Could not resolve gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.12.0.
         > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.12.0/license-gradle-plugin-0.12.0.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.12.0/license-gradle-plugin-0.12.0.pom'.
               > Connect to gradleware-plugins.s3.amazonaws.com:443 [gradleware-plugins.s3.amazonaws.com/54.231.12.161] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 29.256 secs

**Comment by SunZhaonan** [comment]
This `license-gradle-plugin-0.12.0.pom` is only used for license header checking. I guess your problem is still because China domain restriction. Try to ping `plugins.gradle.org` to see if you can get respond.

If I'm correct, you can choose one of the following:
* Disable this plugin in the gradle file when you build.
* Download through https://github.com/hierynomus/license-gradle-plugin, put the jar file into your lib
* Use some VPN to access the outer network

Recommend solution 3 as there may be other parts also need to access network outside GFW.
